server:
  port: 8083

spring:
  application:
    name: driver-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rideflux_driver
    username: postgres
    password: postgres

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/rideflux_driver
    user: postgres
    password: postgres

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO